name: Deploy Frontend to EC2

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build project
        env:
          CI: false
          API_URL: ${{ secrets.API_URL }}
          TOKEN_CONTRACT_ADDRESS: ${{ secrets.TOKEN_CONTRACT_ADDRESS }}
        run: |
          npm ci
          npm run build

      - name: Copy build folder to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/"
          target: "/home/${{ secrets.EC2_USER }}/build/"
          recursive: true

      - name: Restart frontend.service on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # (Opcional) Si modificaste el unit file, recarga systemd:
            # sudo systemctl daemon-reload

            # Asegúrate de que la carpeta build existe
            ls -la /home/${{ secrets.EC2_USER }}/build

            # Reinicia el servicio para que use la nueva build
            sudo systemctl restart frontend.service

            # Muestra estado para depuración
            sudo systemctl status frontend.service --no-pager

