name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:                         
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        env:
          CI: false
          API_URL: ${{ secrets.API_URL }}
          TOKEN_CONTRACT_ADDRESS: ${{ secrets.TOKEN_CONTRACT_ADDRESS }}
        run: npm run build


      - name: Archive build artifacts
        run: zip -r build.zip build

      - name: Copy build to EC2 via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build.zip"
          target: "/home/${{ secrets.EC2_USER }}"


      - name: Deploy and run 'serve'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}

            # 2) Instalar 'serve' globalmente sin sudo
            npm install -g serve

            # 3) Desplegar el build
            rm -rf build
            unzip -o build.zip -d build

            # 4) Parar procesos previos de 'serve'
            pkill -f "serve -s build" || true

            # 5) Arrancar el servidor estático en background
            nohup serve -s build -l 80 > serve.log 2>&1 &

            # 6) Verificar que se levantó
            pgrep -fl "serve -s build"
